-- One to Many

CREATE TABLE IF NOT EXISTS Person(
	person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	fullname varchar(300) NOT NULL UNIQUE,
	year_of_birth int CHECK(year_of_birth >= 1900 AND year_of_birth <= 2022)
);

CREATE TABLE IF NOT EXISTS Book(
	book_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	person_id int REFERENCES Person(person_id) ON DELETE SET NULL,
	name varchar(100) NOT NULL,
	author varchar(100) NOT NULL,
	year int
);